name: Lint Code with ESLint and Deploy

on:
  push:
    branches:
      - main

jobs:
  eslint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: |
          npm install

      - name: Run ESLint
        run: |
          npx eslint .

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: eslint
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H 15.188.63.103 >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -t ubuntu@15.188.63.103 <<EOF
            cd MemoMateBackend
            git pull
            sudo systemctl restart memomate-service.service
          EOF
